[package]
name = "nostrkeytool"
version = "0.1.0"
authors = ["Daniel Cadenas"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "4.4.18"
nostr-sdk = "0.27"
tokio = { version = "1", features = ["full"] }
